### ISSUE TITLE
Update Monorepo configuration

### ISSUE THREAD

**Issue by arantespp** [ttoss/monorepo#1]
Remove config folder and use `rc.js` files on the root folder.

### Libs to be configured:

- [ ] ESLint
- [ ] Prettier
- [ ] TypeScript
- [ ] NPM Check Updates
- [ ] Husky 4
- [ ] Commit Lint
- [ ] Lerna
- [ ] Yarn Workspaces

**Comment by RayzaOliveira** [comment]
The settings were made, but I could not open the PR, because I do not have access yet. Could @arantespp  release it for me?

![image](https://user-images.githubusercontent.com/52584988/112233649-94981d00-8c19-11eb-8772-4d892a8ebce5.png)

**Comment by arantespp** [comment]
@RayzaOliveira I give the access to you.

**Comment by RayzaOliveira** [comment]
I just created a [PR](https://github.com/ttoss/monorepo/pull/2) of the modifications I made, could @arantespp  check if everything is ok?
